#!/usr/bin/env python3
"""
Video Dubbing Script - Generated by EmittersWebsite
====================================================
Downloads a YouTube video, transcribes it, translates to target language,
generates TTS audio, and mixes it with the original.

Requirements:
    pip install yt-dlp openai-whisper srt googletrans==4.0.0rc1 edge-tts
    Also requires: ffmpeg (system install)

Usage:
    python dubbed_video.py
"""

import asyncio
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import timedelta
from pathlib import Path

# ============================================================
# CONFIGURATION - Edit these values if needed
# ============================================================
YOUTUBE_URL = "{{YOUTUBE_URL}}"
TARGET_LANG = "{{TARGET_LANG}}"
WHISPER_MODEL = "base"  # tiny, base, small, medium, large
ORIGINAL_VOLUME = 0.2  # Original audio volume (0-1)
OUTPUT_DIR = str(Path.home() / "Desktop")  # Output to Desktop

# ============================================================
# Voice mapping
# ============================================================
EDGE_VOICES = {
    "fr": "fr-FR-HenriNeural",  # Male French
    "pt": "pt-BR-AntonioNeural",  # Male Portuguese
}


def check_dependencies():
    """Check that all required tools are installed."""
    print("[check] Verifying dependencies...")

    # Check Python packages
    missing = []
    for pkg, import_name in [
        ("yt-dlp", "yt_dlp"),
        ("whisper", "whisper"),
        ("srt", "srt"),
        ("googletrans", "googletrans"),
        ("edge_tts", "edge_tts"),
    ]:
        try:
            __import__(import_name)
        except ImportError:
            missing.append(pkg)

    if missing:
        print(f"[check] Missing Python packages: {', '.join(missing)}")
        print(f"[check] Install with: pip install {' '.join(missing)}")
        sys.exit(1)

    # Check system tools
    for tool in ["yt-dlp", "ffmpeg", "ffprobe"]:
        if shutil.which(tool) is None:
            print(f"[check] Missing system tool: {tool}")
            if tool == "yt-dlp":
                print("[check] Install with: pip install yt-dlp")
            else:
                print("[check] Install ffmpeg from https://ffmpeg.org/download.html")
            sys.exit(1)

    print("[check] All dependencies OK")


def download_video(url, output_dir):
    """Download video and extract audio."""
    os.makedirs(output_dir, exist_ok=True)

    print(f"\n[STEP 1/5] Downloading video...")
    print(f"  URL: {url}")

    # Download video
    subprocess.run(
        [
            "yt-dlp",
            "-f",
            "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
            "--merge-output-format",
            "mp4",
            "-o",
            os.path.join(output_dir, "video.%(ext)s"),
            url,
        ],
        check=True,
    )

    # Find downloaded video
    video_path = None
    for f in os.listdir(output_dir):
        if f.startswith("video.") and f.endswith((".mp4", ".mkv", ".webm")):
            video_path = os.path.join(output_dir, f)
            break

    if not video_path:
        raise FileNotFoundError("Video download failed")

    # Extract audio as WAV for Whisper
    print("  Extracting audio...")
    audio_path = os.path.join(output_dir, "audio.wav")
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-i",
            video_path,
            "-vn",
            "-acodec",
            "pcm_s16le",
            "-ar",
            "16000",
            "-ac",
            "1",
            audio_path,
        ],
        check=True,
        capture_output=True,
    )

    print(f"  Video: {video_path}")
    print(f"  Audio: {audio_path}")
    return video_path, audio_path


def transcribe_audio(audio_path, model_size="base"):
    """Transcribe audio to SRT."""
    import whisper
    import srt as srt_lib

    print(f"\n[STEP 2/5] Transcribing with Whisper ({model_size})...")

    model = whisper.load_model(model_size)
    result = model.transcribe(audio_path, word_timestamps=True)

    subtitles = []
    for i, seg in enumerate(result["segments"], start=1):
        subtitles.append(
            srt_lib.Subtitle(
                index=i,
                start=timedelta(seconds=seg["start"]),
                end=timedelta(seconds=seg["end"]),
                content=seg["text"].strip(),
            )
        )

    srt_path = os.path.join(os.path.dirname(audio_path), "transcript.srt")
    with open(srt_path, "w", encoding="utf-8") as f:
        f.write(srt_lib.compose(subtitles))

    print(f"  Generated {len(subtitles)} subtitle segments")
    return srt_path


def translate_srt(srt_path, target_lang):
    """Translate SRT to target language."""
    import srt as srt_lib
    from googletrans import Translator

    print(f"\n[STEP 3/5] Translating to {target_lang}...")

    with open(srt_path, "r", encoding="utf-8") as f:
        subtitles = list(srt_lib.parse(f.read()))

    translator = Translator()
    translated = []

    for i in range(0, len(subtitles), 20):
        batch = subtitles[i : i + 20]
        try:
            results = translator.translate([s.content for s in batch], dest=target_lang)
            for sub, trans in zip(batch, results):
                text = re.sub(r"([.!?:])([A-ZÀ-ÖØ-Þa-zà-öø-ÿ])", r"\1 \2", trans.text)
                text = re.sub(r"  +", " ", text).strip()
                translated.append(
                    srt_lib.Subtitle(
                        index=sub.index,
                        start=sub.start,
                        end=sub.end,
                        content=text,
                    )
                )
        except Exception as e:
            print(f"  Warning: batch failed ({e}), trying one-by-one...")
            for sub in batch:
                try:
                    trans = translator.translate(sub.content, dest=target_lang)
                    translated.append(
                        srt_lib.Subtitle(
                            index=sub.index,
                            start=sub.start,
                            end=sub.end,
                            content=trans.text,
                        )
                    )
                except Exception:
                    translated.append(sub)

    out_path = os.path.join(os.path.dirname(srt_path), f"transcript_{target_lang}.srt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(srt_lib.compose(translated))

    print(f"  Translated {len(translated)} segments")
    return out_path


def generate_tts(translated_srt_path, lang, output_dir):
    """Generate TTS audio segments."""
    import srt as srt_lib
    import edge_tts

    print(f"\n[STEP 4/5] Generating TTS ({EDGE_VOICES.get(lang, lang)})...")

    voice = EDGE_VOICES.get(lang, lang)
    os.makedirs(output_dir, exist_ok=True)

    with open(translated_srt_path, "r", encoding="utf-8") as f:
        subtitles = list(srt_lib.parse(f.read()))

    segments = []

    async def process():
        for sub in subtitles:
            text = re.sub(r"[^\w\s.,;:!?'\-]", "", sub.content, flags=re.UNICODE)
            text = re.sub(r"\s+", " ", text).strip()
            if not text:
                continue

            audio_path = os.path.join(output_dir, f"seg_{sub.index:04d}.wav")
            try:
                comm = edge_tts.Communicate(text, voice)
                await comm.save(audio_path)
                if os.path.exists(audio_path) and os.path.getsize(audio_path) > 0:
                    segments.append(
                        {
                            "index": sub.index,
                            "start": sub.start.total_seconds(),
                            "end": sub.end.total_seconds(),
                            "audio_path": audio_path,
                        }
                    )
                    print(f"  [{sub.index:04d}] OK")
                else:
                    print(f"  [{sub.index:04d}] FAILED (empty)")
            except Exception as e:
                print(f"  [{sub.index:04d}] ERROR: {e}")

    asyncio.run(process())

    # Save metadata
    meta_path = os.path.join(output_dir, "segments.json")
    with open(meta_path, "w") as f:
        json.dump(segments, f, indent=2)

    print(f"  Generated {len(segments)}/{len(subtitles)} segments")
    return segments


def mix_audio(video_path, tts_dir, original_volume=0.2, output_path=None):
    """Mix original video with TTS segments."""
    print(f"\n[STEP 5/5] Mixing audio...")

    # Get video duration
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", video_path],
        capture_output=True,
        text=True,
    )
    duration = float(json.loads(result.stdout)["format"]["duration"])

    # Load segment metadata
    meta_path = os.path.join(tts_dir, "segments.json")
    with open(meta_path) as f:
        segments = json.load(f)

    # Build FFmpeg filter
    inputs = ["-i", video_path]
    filter_parts = [f"[0:a]volume={original_volume}[original]"]
    delayed = []

    for i, seg in enumerate(segments):
        inputs.extend(["-i", seg["audio_path"]])
        delay_ms = int(seg["start"] * 1000)
        label = f"d{i}"
        filter_parts.append(f"[{i + 1}:a]adelay={delay_ms}|{delay_ms}[{label}]")
        delayed.append(f"[{label}]")

    if delayed:
        n = len(delayed)
        filter_parts.append(
            f"{''.join(delayed)}amix=inputs={n}:duration=longest:dropout_transition=0:normalize=0[tts_raw]"
        )
        filter_parts.append(f"[tts_raw]apad=whole_dur={int(duration * 1000)}[tts]")
        filter_parts.append(
            f"[original][tts]amix=inputs=2:duration=first:dropout_transition=0:normalize=0[aout]"
        )
        aout_label = "[aout]"
    else:
        filter_parts.append("[original]anull[aout]")
        aout_label = "[aout]"

    if output_path is None:
        base, ext = os.path.splitext(video_path)
        output_path = f"{base}_dubbed.mp4"

    cmd = [
        "ffmpeg",
        "-y",
        *inputs,
        "-filter_complex",
        ";".join(filter_parts),
        "-map",
        "0:v",
        "-map",
        aout_label,
        "-c:v",
        "copy",
        "-c:a",
        "aac",
        "-b:a",
        "192k",
        "-shortest",
        output_path,
    ]

    subprocess.run(cmd, check=True, capture_output=True)
    print(f"  Output: {output_path}")
    return output_path


def main():
    print("=" * 60)
    print("  VIDEO DUBBING PIPELINE")
    print(f"  URL: {YOUTUBE_URL}")
    print(f"  Language: {TARGET_LANG}")
    print("=" * 60)

    check_dependencies()

    work_dir = tempfile.mkdtemp(prefix="dub_")
    print(f"\n[workspace] {work_dir}")

    try:
        video_path, audio_path = download_video(YOUTUBE_URL, work_dir)
        srt_path = transcribe_audio(audio_path, WHISPER_MODEL)
        translated_path = translate_srt(srt_path, TARGET_LANG)
        tts_dir = os.path.join(work_dir, "tts_segments")
        generate_tts(translated_path, TARGET_LANG, tts_dir)

        # Copy output to Desktop
        timestamp = re.sub(r"[^\d]", "", str(__import__("datetime").datetime.now()))[
            :14
        ]
        output_name = f"dubbed_{TARGET_LANG}_{timestamp}.mp4"
        output_path = os.path.join(OUTPUT_DIR, output_name)
        mix_audio(video_path, tts_dir, ORIGINAL_VOLUME, output_path)

        print("\n" + "=" * 60)
        print(f"  DONE! Dubbed video saved to:")
        print(f"  {output_path}")
        print("=" * 60)

    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
