"use client";

import { Brain } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import OpenPositionsCard from './OpenPositionsCard';
import ReportCard from './ReportCard';
import SummarySection from './SummarySection';
import HistoryAgentCard from './agents/HistoryAgentCard';
import MasterAgentCard from './agents/MasterAgentCard';
import NewsAgentCard from './agents/NewsAgentCard';
import RiskAgentCard from './agents/RiskAgentCard';
import TrendAgentCard from './agents/TrendAgentCard';
import AgentStructuredOutput, { OutputField } from './agents/AgentStructuredOutput';

interface AIAnalysis {
  timestamp: string;
  symbol: string;
  price: number;
  trend: string;
  patterns: string[];
  rsi: number | null;
  confidence: number;
  signal: string;
  reasoning: string;
}

interface Trade {
  id: string;
  type: string;
  price: number;
  openPrice?: number;
  lot: number;
  time: string;
  result?: 'WIN' | 'LOSS';
  pnl?: number;
  profit?: number;
  commission?: number;
  netProfit?: number;
  isOpen?: boolean;
}

export interface ReportMetrics {
  bestTrade: number;
  worstTrade: number;
  avgWin: number;
  avgLoss: number;
  avgTrade: number;
  profitFactor: number;
  maxDrawdown: number;
  expectancy: number;
  longestWinStreak: number;
  longestLoseStreak: number;
  totalGrossProfit: number;
  totalGrossLoss: number;
}

interface NoteItem {
  id: string;
  content: string;
  addedAt: string;
  lastUpdatedAt: string;
  status: 'active' | 'deprecated';
}

interface Notes {
  cycleNumber: number;
  totalTrades: number;
  generatedAt: string;
  items: NoteItem[];
  summary: string;
}

interface GlobalRecommendation {
  lastUpdatedAt: string;
  totalTrades: number;
  recommendation: string;
  keyInsights: string[];
}

interface ReportHistory {
  notes50: Notes | null;
  notes500: Notes | null;
  globalRecommendation: GlobalRecommendation | null;
}

export interface BotStats {
  totalTrades: number;
  wins: number;
  losses: number;
  winRate: number;
  totalPnl: number;
  currentStreak: number;
}

export interface SimulatedAgentOutput {
  trend: {
    direction: 'BUY' | 'SELL' | 'NEUTRAL';
    score: number;
    ma_9?: number;
    ma_21?: number;
    ma_50?: number;
    ma_50_trend?: 'Uptrend' | 'Downtrend' | 'Neutral';
    crossover_status?: 'UP' | 'DOWN' | 'NONE';
    entry_allowed?: boolean;
    reasoning?: string;
    // Timezone-safe candle age: seconds-since-open as computed by the server
    // from the broker's own two clocks, plus the local Date.now() at the
    // moment we fetched it — together these let the card tick up live
    // (candle_age_seconds + elapsed-since-measured_at) without ever needing
    // to compare a broker timestamp directly to the browser's clock.
    candle_age_seconds?: number;
    candle_age_measured_at?: number;
  };
  history: { rrTarget: string; consistency: number; score: number };
  risk: { slDistance: number; tpRatio: string; positionSize: string; score: number };
  news: { sentiment: 'Bullish' | 'Neutral' | 'Bearish'; volatility: number; score: number; approved?: boolean; high_impact_count?: number; rejection_reason?: string | null;
    // Plain-language "explain it like I'm not a trader" recap of today's top
    // headlines, generated by the News Agent so non-expert users build
    // economic understanding over time instead of just seeing raw metrics.
    plain_summary?: string | null };
}

interface AIReportsSectionProps {
  aiAnalysis: AIAnalysis | null;
  openPositions: Trade[];
  floatingPnL: { [key: string]: number };
  newPositionIds: Set<string>;
  stats: BotStats;
  reports: ReportMetrics;
  history: Trade[];
  report: any;
  reportLoading: boolean;
  reportHistory: ReportHistory | null;
  generateReport: (tradeCount: number) => void;
  fetchReportHistory?: () => void;
  onCloseReport: () => void;
  lastSignal?: { signal: string; timestamp: string } | null;
  simulatedAgents?: SimulatedAgentOutput | null;
  latestNews?: any[];
  fetchNews?: () => Promise<void>;
  debugMode?: boolean;
  onDebugSignal?: (signal: 'BUY' | 'SELL') => void;
}


interface AgentReport {
  id: string;
  timestamp: string;
  content: string;
  type: 'insight' | 'alert' | 'update';
}

interface AgentRules {
  agentName: string;
  rules: string[];
  lastModified: string;
}

function formatTimeAgo(timestamp: string): string {
  const now = new Date();
  const then = new Date(timestamp);
  const seconds = Math.floor((now.getTime() - then.getTime()) / 1000);

  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}

// Risk Agent automatic position sizing calculator
function calculatePositionSize(
  accountSize: number,
  riskPercentage: number,
  history: Trade[]
): { positionSize: string; recommendedLots: number; riskAmount: number } {
  if (history.length === 0) {
    return { positionSize: '0.01', recommendedLots: 0.01, riskAmount: 0 };
  }

  // Calculate average pip distance from recent trades
  const recentTrades = history.slice(-10);
  let totalPipDistance = 0;
  recentTrades.forEach(trade => {
    const pipDist = Math.abs((trade.price - (trade.openPrice || trade.price)) * 10000);
    totalPipDistance += pipDist;
  });
  const avgPipDistance = totalPipDistance / recentTrades.length || 50; // Default 50 pips if no data

  // Risk Amount = Account Size * Risk Percentage
  const riskAmount = accountSize * (riskPercentage / 100);

  // Position Size = Risk Amount / (Pip Distance * Pip Value)
  // For forex, pip value is typically 10 per standard lot
  const pipValue = 10;
  const positionSizeUnits = riskAmount / (avgPipDistance * (pipValue / 10));
  const lotSize = Math.round((positionSizeUnits / 100000) * 1000) / 1000; // Convert to standard lots

  return {
    positionSize: `${Math.max(0.01, Math.min(0.1, lotSize)).toFixed(2)} lots`,
    recommendedLots: Math.max(0.01, Math.min(0.1, lotSize)),
    riskAmount: Math.round(riskAmount * 100) / 100,
  };
}

export default function AIReportsSection({
  aiAnalysis,
  openPositions,
  floatingPnL,
  newPositionIds,
  stats,
  reports,
  history,
  report,
  reportLoading,
  reportHistory,
  generateReport,
  fetchReportHistory,
  onCloseReport,
  lastSignal,
  simulatedAgents,
  latestNews,
  fetchNews,
  debugMode = false,
  onDebugSignal,
}: AIReportsSectionProps) {
  const [selectedAgent, setSelectedAgent] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'rules' | 'reports' | 'state'>('rules');
  const [agentLastRun, setAgentLastRun] = useState<{
    risk: string;
    trend: string;
    news: string;
    history: string;
    master: string;
  }>({
    risk: new Date().toISOString(),
    trend: new Date().toISOString(),
    news: new Date().toISOString(),
    history: new Date().toISOString(),
    master: new Date().toISOString(),
  });
  const [activeAgent, setActiveAgent] = useState<string | null>(null);
  const [lastNewsFetchTime, setLastNewsFetchTime] = useState<number>(0);

  // Risk Agent: user-configurable drawdown limits (daily/weekly/monthly %),
  // persisted server-side in risk_settings.json and enforced by the real
  // Risk Agent gatekeeper. Edited from the Risk Agent's Rules panel below.
  // Mirrors DEFAULT_SETTINGS in /api/trading-bot/risk-settings/route.ts —
  // used by the "Reset to Default" button to restore sane starting values.
  const DEFAULT_RISK_SETTINGS = { daily_drawdown_pct: 5, weekly_drawdown_pct: 7.5, monthly_drawdown_pct: 10 };
  const [riskSettings, setRiskSettings] = useState<{ daily_drawdown_pct: number; weekly_drawdown_pct: number; monthly_drawdown_pct: number } | null>(null);
  const [riskSettingsDraft, setRiskSettingsDraft] = useState<{ daily: string; weekly: string; monthly: string }>({ daily: '', weekly: '', monthly: '' });
  const [riskSettingsSaving, setRiskSettingsSaving] = useState(false);
  const [riskSettingsSavedAt, setRiskSettingsSavedAt] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/api/trading-bot/risk-settings')
      .then(res => res.ok ? res.json() : null)
      .then(data => {
        if (cancelled || !data) return;
        setRiskSettings(data);
        setRiskSettingsDraft({
          daily: String(data.daily_drawdown_pct),
          weekly: String(data.weekly_drawdown_pct),
          monthly: String(data.monthly_drawdown_pct),
        });
      })
      .catch(() => {});
    return () => { cancelled = true; };
  }, []);

  const saveRiskSettings = async () => {
    setRiskSettingsSaving(true);
    try {
      const res = await fetch('/api/trading-bot/risk-settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          daily_drawdown_pct: parseFloat(riskSettingsDraft.daily),
          weekly_drawdown_pct: parseFloat(riskSettingsDraft.weekly),
          monthly_drawdown_pct: parseFloat(riskSettingsDraft.monthly),
        }),
      });
      if (res.ok) {
        const data = await res.json();
        setRiskSettings(data);
        setRiskSettingsDraft({
          daily: String(data.daily_drawdown_pct),
          weekly: String(data.weekly_drawdown_pct),
          monthly: String(data.monthly_drawdown_pct),
        });
        setRiskSettingsSavedAt(Date.now());
        console.log(`[RISK SETTINGS] Saved → daily ${data.daily_drawdown_pct}% | weekly ${data.weekly_drawdown_pct}% | monthly ${data.monthly_drawdown_pct}%`);
      }
    } catch (e) {
      console.error('[RISK SETTINGS] Save failed:', e);
    } finally {
      setRiskSettingsSaving(false);
    }
  };

  // Risk Agent: Automatically calculate position sizes
  const positionSizing = useMemo(() => {
    const accountSize = Math.max(1000, stats.totalPnl + 10000);
    const riskPercentage = 2; // Default 2% risk per trade
    return calculatePositionSize(accountSize, riskPercentage, history);
  }, [stats.totalPnl, history]);

  // Prepare latest news for display (top 3)
  const displayNews = useMemo(() => {
    return (latestNews || []).slice(0, 3);
  }, [latestNews]);

  // Update agent last run times when data changes
  // Risk Agent: data-driven in normal mode, simulated in debug mode
  useEffect(() => {
    if (!simulatedAgents) {
      // Update lastRun on successful data reception
      setAgentLastRun(prev => ({ ...prev, risk: new Date().toISOString() }));
      setActiveAgent('risk');
      console.log(`[RISK AGENT] ✓ Received data at ${new Date().toLocaleTimeString()} | Drawdown: ${reports.maxDrawdown.toFixed(2)}% | P&L: $${stats.totalPnl.toFixed(2)}`);
      const timer = setTimeout(() => setActiveAgent(null), 2500);
      return () => clearTimeout(timer);
    }
  }, [reports.maxDrawdown, stats.totalPnl, simulatedAgents]);

  // Debug mode: Risk Agent random trigger
  useEffect(() => {
    if (simulatedAgents) {
      const riskInterval = setInterval(() => {
        setActiveAgent('risk');
        setAgentLastRun(prev => ({ ...prev, risk: new Date().toISOString() }));
        console.log(`[RISK AGENT] 🛡️ Active | Simulated risk check`);
        const timer = setTimeout(() => setActiveAgent(null), 2500);
        return () => clearTimeout(timer);
      }, 8000 + Math.random() * 4000); // 8-12s random interval
      return () => clearInterval(riskInterval);
    }
  }, [simulatedAgents]);

  // Trend Agent: data-driven in normal mode, simulated in debug mode
  useEffect(() => {
    if (!simulatedAgents) {
      // Update lastRun on successful data reception
      setAgentLastRun(prev => ({ ...prev, trend: new Date().toISOString() }));
      setActiveAgent('trend');
      const trend = reports.longestWinStreak > 3 ? 'UPTREND' : reports.longestLoseStreak > 3 ? 'DOWNTREND' : 'NEUTRAL';
      console.log(`[TREND AGENT] ✓ Received data at ${new Date().toLocaleTimeString()} | Trend: ${trend} | W:${reports.longestWinStreak} L:${reports.longestLoseStreak}`);
      const timer = setTimeout(() => setActiveAgent(null), 2500);
      return () => clearTimeout(timer);
    }
  }, [reports.longestWinStreak, reports.longestLoseStreak, simulatedAgents]);

  // Trend Agent: keep the "X ago" badge honest — bump lastRun only when the
  // REAL agent actually ran (page.tsx posts to /api/trading-bot/agents/trend
  // exactly once per new candle and stores the resulting `reasoning`). Tying
  // the timestamp to that field — rather than to win/loss-streak churn —
  // means the badge reflects the true once-per-candle cadence read straight
  // from ma_data.json's timestamp change, instead of drifting to 2m+.
  useEffect(() => {
    if (simulatedAgents?.trend?.reasoning) {
      setAgentLastRun(prev => ({ ...prev, trend: new Date().toISOString() }));
    }
  }, [simulatedAgents?.trend?.reasoning]);

  // News Agent: Trigger animation only when news data arrives
  useEffect(() => {
    if (latestNews && latestNews.length > 0) {
      setActiveAgent('news');
      setAgentLastRun(prev => ({ ...prev, news: new Date().toISOString() }));
      console.log(`[NEWS AGENT] 📰 Active | Received ${latestNews.length} news items`);
      const timer = setTimeout(() => setActiveAgent(prev => prev === 'news' ? null : prev), 2500);
      return () => clearTimeout(timer);
    }
  }, [latestNews]);

  // News Agent: Real-time polling from API (30s rate limit)
  useEffect(() => {
    const newsInterval = setInterval(() => {
      const now = Date.now();
      if (fetchNews && now - lastNewsFetchTime >= 30000) {
        fetchNews();
        setLastNewsFetchTime(now);
      }
    }, 30000);
    return () => clearInterval(newsInterval);
  }, [fetchNews, lastNewsFetchTime]);

  // History Agent: data-driven in normal mode, simulated in debug mode
  // Triggers on new trade insertion OR report updates
  useEffect(() => {
    if (!simulatedAgents) {
      // Normal mode: trigger when new trades are added OR reports update
      const shouldTrigger = history.length > 0 && (
        reportHistory?.globalRecommendation?.lastUpdatedAt ||
        history.length > 0
      );

      if (shouldTrigger) {
        setActiveAgent('history');
        setAgentLastRun(prev => ({ ...prev, history: new Date().toISOString() }));
        console.log(`[HISTORY AGENT] 📊 Active | Analyzing ${history.length} trades for performance insights`);
        const timer = setTimeout(() => setActiveAgent(null), 2500);
        return () => clearTimeout(timer);
      }
    }
  }, [history.length, reportHistory?.globalRecommendation?.lastUpdatedAt, simulatedAgents]);

  // Debug mode: History Agent random trigger
  useEffect(() => {
    if (simulatedAgents) {
      const historyInterval = setInterval(() => {
        setActiveAgent('history');
        setAgentLastRun(prev => ({ ...prev, history: new Date().toISOString() }));
        console.log(`[HISTORY AGENT] 📊 Active | Simulated history analysis`);
        const timer = setTimeout(() => setActiveAgent(null), 2500);
        return () => clearTimeout(timer);
      }, 12000 + Math.random() * 5000); // 12-17s random interval
      return () => clearInterval(historyInterval);
    }
  }, [simulatedAgents]);

  // Master Agent triggers only when sub-agents are active
  useEffect(() => {
    if (activeAgent && activeAgent !== 'master' && ['risk', 'trend', 'news', 'history'].includes(activeAgent)) {
      // Trigger master after sub-agent completes its initial phase
      const masterDelay = setTimeout(() => {
        setActiveAgent('master');
        setAgentLastRun(prev => ({ ...prev, master: new Date().toISOString() }));
        console.log(`[MASTER AGENT] 🧠 Active | Aggregating signals from ${activeAgent} agent`);

        // Master runs for 2.5s, then clears
        const masterTimer = setTimeout(() => {
          setActiveAgent(null);
        }, 2500);

        return () => clearTimeout(masterTimer);
      }, 1200); // Trigger after first sub-agent's pulse completes

      return () => clearTimeout(masterDelay);
    }
  }, [activeAgent]);

  // Master Agent triggers on debug signal (manual trigger)
  useEffect(() => {
    if (lastSignal) {
      setActiveAgent('master');
      setAgentLastRun(prev => ({ ...prev, master: new Date().toISOString() }));
      console.log(`[MASTER AGENT] 🤖 Signal: ${lastSignal.signal} | Time: ${new Date(lastSignal.timestamp).toLocaleTimeString()} | Status: EXECUTING`);
      const timer = setTimeout(() => setActiveAgent(null), 2500);
      return () => clearTimeout(timer);
    }
  }, [lastSignal]);

  // Sample agent reports (would come from backend)
  const agentReportsData: { [key: string]: AgentReport[] } = {
    risk: [
      { id: '1', timestamp: '2026-05-30 14:32', content: 'Drawdown increased to 45% - within limits', type: 'update' },
      { id: '2', timestamp: '2026-05-30 12:15', content: 'Risk threshold breached temporarily', type: 'alert' },
    ],
    trend: [
      { id: '1', timestamp: '2026-05-30 14:45', content: 'Winning streak reached 5 - strong uptrend detected', type: 'insight' },
      { id: '2', timestamp: '2026-05-30 11:30', content: 'Trend momentum shifting upward', type: 'update' },
    ],
    news: [
      { id: '1', timestamp: '2026-05-30 14:20', content: 'No major economic news events detected', type: 'update' },
    ],
    history: [
      { id: '1', timestamp: '2026-05-30 13:00', content: '50-trade report: Win rate improved to 62%', type: 'insight' },
    ],
  };

  // Sample agent rules
  const agentRulesData: { [key: string]: AgentRules } = {
    risk: {
      agentName: 'Risk Management',
      rules: [
        'Max drawdown threshold: 50% of total P&L',
        'Position size based on volatility',
        'Stop loss at 2% below entry',
        'Reduce size on consecutive losses',
      ],
      lastModified: '2026-05-28 10:30',
    },
    trend: {
      agentName: 'Probability & Trend',
      rules: [
        'Uptrend detection: Win streak > 3',
        'Downtrend detection: Loss streak > 3',
        'Neutral zone: Win/loss <= 3',
        'Trend change requires 2 opposite signals',
      ],
      lastModified: '2026-05-25 15:45',
    },
    news: {
      agentName: 'Economic News',
      rules: [
        'Fetch news from external API (Finnhub/NewsAPI/FinancialJuice) every 5 minutes',
        'AI/LLM analyzes news sentiment and impact on market',
        'Display top 3 news headlines with sentiment badges in News Agent card',
        'High impact events: Extend stop loss 2x',
        'No major events = 25% weight baseline',
        'Breaking news triggers immediate alert',
        'AI generates news-based reports for decision making',
      ],
      lastModified: '2026-05-30 23:45',
    },
    history: {
      agentName: 'History & Reports',
      rules: [
        'Generate 50-trade reports at milestones',
        'Generate 500-trade reports at milestones',
        'Analyze win rate vs R:R correlation',
        'Detect seasonal patterns',
        'Compare against baseline performance',
      ],
      lastModified: '2026-05-22 14:20',
    },
  };

  return (
    <div className="col-span-5 bg-white/[0.02] border border-white/[0.05] flex flex-col min-h-0 rounded h-full">
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/[0.05] shrink-0">
        <div className="flex items-center gap-2">
          <Brain className="w-3.5 h-3.5 text-violet-400/60" />
          <h2 className="text-[11px] font-semibold text-white/70 tracking-wide">AI & Reports</h2>
        </div>
      </div>
      <div className="flex-1 min-h-0 overflow-y-auto p-4">
        <div className="grid grid-cols-6 gap-3 h-auto auto-rows-max">
          {/* Middle: Recommendations + Open Positions — 2 cols */}
          <div className="col-span-3 flex flex-col gap-3">

            {/* Sub-Agent Reports */}
            <div className="grid grid-cols-2 gap-2">
              <style>{`
                /* ── Single pulse keyframe – color injected via CSS custom property ── */
                @keyframes agentPulse {
                  0%   { box-shadow: 0 0 0px 0px var(--ac), inset 0 0 0px  0px var(--ac-in); }
                  25%  { box-shadow: 0 0 16px 6px var(--ac), inset 0 0 12px 2px var(--ac-in); }
                  50%  { box-shadow: 0 0 8px  0px var(--ac), inset 0 0 6px  0px var(--ac-in); }
                  75%  { box-shadow: 0 0 16px 6px var(--ac), inset 0 0 12px 2px var(--ac-in); }
                  100% { box-shadow: 0 0 0px  0px var(--ac), inset 0 0 0px  0px var(--ac-in); }
                }
                @keyframes agentTextGlow {
                  0%,100% { text-shadow: none; }
                  25%,75% { text-shadow: 0 0 10px var(--ac-text); }
                  50%     { text-shadow: 0 0 5px  var(--ac-text); }
                }
                @keyframes iconRotate {
                  0%   { transform: rotate(0deg)   scale(1);    }
                  50%  { transform: rotate(180deg) scale(1.15); }
                  100% { transform: rotate(360deg) scale(1);    }
                }
                @keyframes progressFlow {
                  0%,100% { opacity: 0.6; }
                  50%     { opacity: 1; filter: drop-shadow(0 0 4px currentColor); }
                }

                /* ── Per-agent color tokens ── */
                .agent-active-trend   { --ac: rgba(34,211,238,0.22);  --ac-in: rgba(34,211,238,0.08);  --ac-text: rgba(34,211,238,0.7);  --ac-drop: rgba(34,211,238,0.5);  --ac-border: rgba(34,211,238,0.35);  }
                .agent-active-history { --ac: rgba(16,185,129,0.22);  --ac-in: rgba(16,185,129,0.08);  --ac-text: rgba(16,185,129,0.7);  --ac-drop: rgba(16,185,129,0.5);  --ac-border: rgba(16,185,129,0.35);  }
                .agent-active-risk    { --ac: rgba(239,68,68,0.22);   --ac-in: rgba(239,68,68,0.08);   --ac-text: rgba(239,68,68,0.7);   --ac-drop: rgba(239,68,68,0.5);   --ac-border: rgba(239,68,68,0.35);   }
                .agent-active-news    { --ac: rgba(168,85,247,0.22);  --ac-in: rgba(168,85,247,0.08);  --ac-text: rgba(168,85,247,0.7);  --ac-drop: rgba(168,85,247,0.5);  --ac-border: rgba(168,85,247,0.35);  }
                .agent-active-master  { --ac: rgba(217,119,6,0.22);   --ac-in: rgba(217,119,6,0.08);   --ac-text: rgba(217,119,6,0.7);   --ac-drop: rgba(217,119,6,0.5);   --ac-border: rgba(217,119,6,0.35);   }

                /* ── Shared active styles (apply the single animation) ── */
                .agent-active-trend,
                .agent-active-history,
                .agent-active-risk,
                .agent-active-news,
                .agent-active-master {
                  animation: agentPulse 2s ease-in-out infinite !important;
                  border-color: var(--ac-border) !important;
                }

                .agent-active-trend   .agent-icon,
                .agent-active-history .agent-icon,
                .agent-active-risk    .agent-icon,
                .agent-active-news    .agent-icon,
                .agent-active-master  .agent-icon {
                  animation: iconRotate 2s ease-in-out infinite !important;
                  filter: drop-shadow(0 0 4px var(--ac-drop)) !important;
                }

                .agent-active-trend   .agent-title,
                .agent-active-history .agent-title,
                .agent-active-risk    .agent-title,
                .agent-active-news    .agent-title,
                .agent-active-master  .agent-title {
                  animation: agentTextGlow 2s ease-in-out infinite !important;
                }

                .agent-active-trend   .progress-bar,
                .agent-active-history .progress-bar,
                .agent-active-risk    .progress-bar,
                .agent-active-news    .progress-bar,
                .agent-active-master  .progress-bar {
                  animation: progressFlow 2s ease-in-out infinite !important;
                }
              `}</style>

              {/* Trend Agent (Foundation) */}
              <TrendAgentCard
                activeAgent={activeAgent}
                agentLastRun={agentLastRun}
                reports={reports}
                simulatedAgents={simulatedAgents}
                onRulesClick={() => {
                  setSelectedAgent('trend');
                  setActiveTab('rules');
                }}
                onReportsClick={() => {
                  setSelectedAgent('trend');
                  setActiveTab('reports');
                }}
                onStateClick={() => {
                  setSelectedAgent('trend');
                  setActiveTab('state');
                }}
                formatTimeAgo={formatTimeAgo}
              />

              {/* News Agent (Context Provider) */}
              <NewsAgentCard
                activeAgent={activeAgent}
                agentLastRun={agentLastRun}
                reports={reports}
                simulatedAgents={simulatedAgents}
                displayNews={displayNews}
                onRulesClick={() => {
                  setSelectedAgent('news');
                  setActiveTab('rules');
                }}
                onReportsClick={() => {
                  setSelectedAgent('news');
                  setActiveTab('reports');
                }}
                onStateClick={() => {
                  setSelectedAgent('news');
                  setActiveTab('state');
                }}
                formatTimeAgo={formatTimeAgo}
              />

              {/* History Agent (Validator) */}
              <HistoryAgentCard
                activeAgent={activeAgent}
                agentLastRun={agentLastRun}
                stats={stats}
                reports={reports}
                simulatedAgents={simulatedAgents}
                reportHistory={reportHistory}
                history={history}
                onRulesClick={() => {
                  setSelectedAgent('history');
                  setActiveTab('rules');
                }}
                onReportsClick={() => {
                  setSelectedAgent('history');
                  setActiveTab('reports');
                }}
                onStateClick={() => {
                  setSelectedAgent('history');
                  setActiveTab('state');
                }}
                formatTimeAgo={formatTimeAgo}
              />

              {/* Risk Agent (Depends on Trend + News) */}
              <RiskAgentCard
                activeAgent={activeAgent}
                agentLastRun={agentLastRun}
                reports={reports}
                stats={stats}
                simulatedAgents={simulatedAgents}
                positionSizing={positionSizing}
                onRulesClick={() => {
                  setSelectedAgent('risk');
                  setActiveTab('rules');
                }}
                onReportsClick={() => {
                  setSelectedAgent('risk');
                  setActiveTab('reports');
                }}
                onStateClick={() => {
                  setSelectedAgent('risk');
                  setActiveTab('state');
                }}
                formatTimeAgo={formatTimeAgo}
              />
            </div>

            {/* Master Agent */}
            <MasterAgentCard
              activeAgent={activeAgent}
              agentLastRun={agentLastRun}
              reports={reports}
              stats={stats}
              simulatedAgents={simulatedAgents}
              formatTimeAgo={formatTimeAgo}
              debugMode={debugMode}
              onDebugSignal={onDebugSignal}
            />
          </div>

          <div className="col-span-1">
            <OpenPositionsCard
              openPositions={openPositions}
              floatingPnL={floatingPnL}
              newPositionIds={newPositionIds}
            />
          </div>

          {/* Report Card & History */}
          <div className="col-span-2">
            <ReportCard
              report={report}
              reportLoading={reportLoading}
              reportHistory={reportHistory}
              onCloseReport={onCloseReport}
              history={history}
              onGenerateReport={fetchReportHistory}
            />

            {/* Left: Live Analysis or Session Summary — 6 cols */}
            <div className="mt-3">
              <SummarySection aiAnalysis={aiAnalysis} stats={stats} reports={reports} />
            </div>
          </div>
        </div>

        {/* Unified Agent Modal with Tabs */}
        {selectedAgent && agentRulesData[selectedAgent] && agentReportsData[selectedAgent] && (() => {
          // Build structured output fields for the selected agent
          const agentStatus = (agent: string): OutputField['value'] => {
            if (activeAgent === agent) return 'analyzing';
            switch (agent) {
              case 'trend':    return simulatedAgents?.trend?.entry_allowed ? 'approved' : simulatedAgents?.trend ? 'rejected' : 'offline';
              case 'risk':     return simulatedAgents?.risk?.score ? 'approved' : simulatedAgents?.risk ? 'rejected' : 'offline';
              case 'history':  return simulatedAgents?.history?.score ? 'approved' : simulatedAgents?.history ? 'rejected' : 'offline';
              case 'news':     return !simulatedAgents?.news ? 'offline' : simulatedAgents.news.approved === false ? 'rejected' : 'approved';
              default:         return 'offline';
            }
          };

          // Human-readable explanation of why each agent approved/rejected
          const agentReason = (agent: string): string | null => {
            switch (agent) {
              case 'trend': {
                if (simulatedAgents?.trend?.reasoning) return simulatedAgents.trend.reasoning;
                if (!simulatedAgents?.trend) return null;
                const { entry_allowed, crossover_status, ma_50_trend } = simulatedAgents.trend;
                if (entry_allowed) return `${crossover_status ?? 'Crossover'} aligned with ${ma_50_trend ?? 'trend'} — entry valid.`;
                if (crossover_status && crossover_status !== 'NONE') return `${crossover_status} crossover detected, but MA50 shows ${ma_50_trend ?? 'no clear trend'} — filtered as noise.`;
                return 'No crossover on the latest completed candle — monitoring for a signal.';
              }
              case 'history': {
                if (!simulatedAgents?.history) return null;
                const { score, consistency, rrTarget } = simulatedAgents.history;
                return score
                  ? `Sufficient sample consistency (${consistency}%) supports an R:R of ${rrTarget} — recommendation passed to Risk Agent.`
                  : `Consistency score too low (${consistency}%) to confidently recommend an R:R — defaulting to conservative ${rrTarget}.`;
              }
              case 'risk': {
                if (!simulatedAgents?.risk) return null;
                const { score, slDistance, tpRatio, positionSize } = simulatedAgents.risk;
                return score
                  ? `Within daily/monthly loss limits and position cap — sized at ${positionSize} lots with SL ${slDistance}% / TP ${tpRatio}.`
                  : `Loss limits, drawdown, or open-position cap breached — trade blocked regardless of size (${positionSize} lots) or SL/TP (${slDistance}% / ${tpRatio}).`;
              }
              case 'news': {
                if (!simulatedAgents?.news) return null;
                if (simulatedAgents.news.approved === false) {
                  return simulatedAgents.news.rejection_reason
                    ? `Blocked: ${simulatedAgents.news.rejection_reason}`
                    : `Blocked due to elevated risk — ${simulatedAgents.news.sentiment} sentiment with ${simulatedAgents.news.high_impact_count ?? 0} high-impact headline(s) and VIX-proxy ${simulatedAgents.news.volatility}.`;
                }
                return `No major risk events — ${simulatedAgents.news.sentiment} sentiment, VIX-proxy ${simulatedAgents.news.volatility}, ${simulatedAgents.news.high_impact_count ?? 0} high-impact headline(s).`;
              }
              default:
                return null;
            }
          };

          const stateFields: Record<string, OutputField[]> = {
            trend: [
              { key: 'agent',         value: 'trend' },
              { key: 'status',        value: agentStatus('trend') },
              { key: 'direction',     value: simulatedAgents?.trend?.direction ?? null },
              { key: 'entry_allowed', value: simulatedAgents?.trend?.entry_allowed ?? null },
              { key: 'crossover',     value: simulatedAgents?.trend?.crossover_status ?? null },
              { key: 'ma_trend',      value: simulatedAgents?.trend?.ma_50_trend ?? null },
              { key: 'ma_9',          value: simulatedAgents?.trend?.ma_9 ?? null },
              { key: 'ma_21',         value: simulatedAgents?.trend?.ma_21 ?? null },
              { key: 'ma_50',         value: simulatedAgents?.trend?.ma_50 ?? null },
              { key: 'score',         value: simulatedAgents?.trend?.score ?? null },
            ],
            history: [
              { key: 'agent',       value: 'history' },
              { key: 'status',      value: agentStatus('history') },
              { key: 'rr_ratio',    value: simulatedAgents?.history?.rrTarget ?? null },
              { key: 'consistency', value: simulatedAgents?.history?.consistency ?? null },
              { key: 'score',       value: simulatedAgents?.history?.score ?? null },
            ],
            risk: [
              { key: 'agent',         value: 'risk' },
              { key: 'status',        value: agentStatus('risk') },
              { key: 'position_size', value: simulatedAgents?.risk?.positionSize ?? null },
              { key: 'sl_pct',        value: simulatedAgents?.risk?.slDistance ?? null },
              { key: 'tp_ratio',      value: simulatedAgents?.risk?.tpRatio ?? null },
              { key: 'score',         value: simulatedAgents?.risk?.score ?? null },
            ],
            news: [
              { key: 'agent',      value: 'news' },
              { key: 'status',     value: agentStatus('news') },
              { key: 'sentiment',  value: simulatedAgents?.news?.sentiment ?? null },
              { key: 'volatility', value: simulatedAgents?.news?.volatility ?? null },
              { key: 'score',      value: simulatedAgents?.news?.score ?? null },
            ],
          };

          return (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-[#0d1117] border border-white/10 rounded-lg max-w-md w-full max-h-96 flex flex-col">
              {/* Header with Tabs */}
              <div className="border-b border-white/10 px-4 pt-3">
                <div className="flex items-center justify-between mb-0">
                  <h3 className="text-sm font-bold text-white">{agentRulesData[selectedAgent].agentName}</h3>
                  <button
                    onClick={() => setSelectedAgent(null)}
                    className="text-white/40 hover:text-white/60 text-lg"
                  >
                    ✕
                  </button>
                </div>
                {/* Tabs */}
                <div className="flex gap-4 mt-3 border-t border-white/[0.05]">
                  <button
                    onClick={() => setActiveTab('rules')}
                    className={`px-3 py-2 text-[11px] font-semibold uppercase tracking-wider border-b-2 transition-colors ${
                      activeTab === 'rules'
                        ? 'border-white text-white'
                        : 'border-transparent text-white/40 hover:text-white/60'
                    }`}
                  >
                    Rules
                  </button>
                  <button
                    onClick={() => setActiveTab('reports')}
                    className={`px-3 py-2 text-[11px] font-semibold uppercase tracking-wider border-b-2 transition-colors ${
                      activeTab === 'reports'
                        ? 'border-white text-white'
                        : 'border-transparent text-white/40 hover:text-white/60'
                    }`}
                  >
                    Reports
                  </button>
                  <button
                    onClick={() => setActiveTab('state')}
                    className={`px-3 py-2 text-[11px] font-semibold uppercase tracking-wider border-b-2 transition-colors ${
                      activeTab === 'state'
                        ? 'border-white text-white'
                        : 'border-transparent text-white/40 hover:text-white/60'
                    }`}
                  >
                    State
                  </button>
                </div>
              </div>

              {/* Content */}
              <div className="flex-1 overflow-y-auto p-4">
                {activeTab === 'rules' ? (
                  <div className="space-y-3">
                    {agentRulesData[selectedAgent].rules.map((rule, i) => (
                      <div key={i} className="flex gap-2">
                        <span className="text-white/30 text-xs mt-1">•</span>
                        <p className="text-xs text-white/60 leading-relaxed">{rule}</p>
                      </div>
                    ))}

                    {/* Risk Agent: editable drawdown-limit preferences — these
                        are persisted to risk_settings.json and enforced
                        directly by the real Risk Agent gatekeeper (the daily/
                        weekly/monthly loss gates use these percentages of
                        account equity, not hardcoded values). */}
                    {selectedAgent === 'risk' && (
                      <div className="pt-3 border-t border-white/10 mt-1 space-y-2.5">
                        <span className="text-[10px] font-bold text-white/40 uppercase tracking-widest">
                          Drawdown Limit Preferences
                        </span>
                        <p className="text-[11px] text-white/40 leading-relaxed">
                          Trades are blocked once realized losses breach these percentages of account equity. Adjust to match your own risk tolerance.
                        </p>
                        {([
                          { key: 'daily',   label: 'Daily limit (%)' },
                          { key: 'weekly',  label: 'Weekly limit (%)' },
                          { key: 'monthly', label: 'Monthly limit (%)' },
                        ] as const).map(({ key, label }) => (
                          <div key={key} className="flex items-center justify-between gap-2">
                            <span className="text-xs text-white/50">{label}</span>
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min={0.1}
                                max={100}
                                step={0.5}
                                value={riskSettingsDraft[key]}
                                onChange={(e) => setRiskSettingsDraft(prev => ({ ...prev, [key]: e.target.value }))}
                                className="w-16 bg-white/[0.05] border border-white/10 rounded px-1.5 py-1 text-xs text-white/80 text-right font-mono focus:outline-none focus:border-white/30"
                              />
                              <span className="text-[10px] text-white/30">%</span>
                            </div>
                          </div>
                        ))}
                        <div className="flex items-center justify-between pt-1">
                          <div className="flex items-center gap-2">
                            <button
                              onClick={saveRiskSettings}
                              disabled={riskSettingsSaving}
                              className="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider rounded bg-emerald-500/15 text-emerald-300/90 border border-emerald-500/20 hover:bg-emerald-500/25 transition-colors disabled:opacity-40"
                            >
                              {riskSettingsSaving ? 'Saving…' : 'Save Preferences'}
                            </button>
                            <button
                              onClick={() => setRiskSettingsDraft({
                                daily: String(DEFAULT_RISK_SETTINGS.daily_drawdown_pct),
                                weekly: String(DEFAULT_RISK_SETTINGS.weekly_drawdown_pct),
                                monthly: String(DEFAULT_RISK_SETTINGS.monthly_drawdown_pct),
                              })}
                              disabled={riskSettingsSaving}
                              title={`Resets the fields to ${DEFAULT_RISK_SETTINGS.daily_drawdown_pct}% / ${DEFAULT_RISK_SETTINGS.weekly_drawdown_pct}% / ${DEFAULT_RISK_SETTINGS.monthly_drawdown_pct}% — click Save Preferences to apply`}
                              className="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider rounded bg-white/[0.04] text-white/40 border border-white/10 hover:bg-white/[0.08] hover:text-white/60 transition-colors disabled:opacity-40"
                            >
                              Reset to Default
                            </button>
                          </div>
                          {riskSettingsSavedAt && Date.now() - riskSettingsSavedAt < 4000 && (
                            <span className="text-[11px] text-emerald-400/70">✓ Saved</span>
                          )}
                          {riskSettings && (
                            <span className="text-[10px] text-white/30 font-mono">
                              Active: {riskSettings.daily_drawdown_pct}% / {riskSettings.weekly_drawdown_pct}% / {riskSettings.monthly_drawdown_pct}%
                            </span>
                          )}
                        </div>
                      </div>
                    )}

                    <div className="pt-3 border-t border-white/10 mt-4">
                      <span className="text-[11px] text-white/30">
                        Last modified: {agentRulesData[selectedAgent].lastModified}
                      </span>
                    </div>
                  </div>
                ) : activeTab === 'reports' ? (
                  <div className="space-y-2">
                    {agentReportsData[selectedAgent]
                      .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
                      .map((rep) => (
                        <div key={rep.id} className="bg-white/[0.03] border border-white/[0.08] p-2.5 rounded">
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-[10px] font-bold text-white/50 uppercase">{rep.type}</span>
                            <span className="text-[10px] text-white/30 font-mono">{rep.timestamp}</span>
                          </div>
                          <p className="text-[11px] text-white/60 leading-relaxed">{rep.content}</p>
                        </div>
                      ))}
                  </div>
                ) : (
                  <div>
                    <p className="text-[10px] text-white/30 mb-3 leading-relaxed">
                      Live output from the last agent run. This is the structured data Master reads to make decisions.
                    </p>
                    {agentReason(selectedAgent) && (
                      <div className={`mb-3 p-2.5 rounded border text-[11px] leading-relaxed ${
                        agentStatus(selectedAgent) === 'approved'
                          ? 'bg-emerald-500/[0.06] border-emerald-500/20 text-emerald-200/80'
                          : agentStatus(selectedAgent) === 'rejected'
                          ? 'bg-red-500/[0.06] border-red-500/20 text-red-200/80'
                          : 'bg-white/[0.03] border-white/[0.08] text-white/50'
                      }`}>
                        <span className="font-bold uppercase tracking-wider text-[9px] block mb-1 opacity-70">
                          Why {agentStatus(selectedAgent) === 'approved' ? 'approved' : agentStatus(selectedAgent) === 'rejected' ? 'rejected' : 'this state'}
                        </span>
                        {agentReason(selectedAgent)}
                      </div>
                    )}
                    {stateFields[selectedAgent] ? (
                      <AgentStructuredOutput fields={stateFields[selectedAgent]} />
                    ) : (
                      <p className="text-xs text-white/30 italic">No state available for this agent.</p>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
          );
        })()}
      </div>
    </div>
  );
}
