version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Next.js default port
      - '24678:24678'  # Vite HMR port
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev"
