//+------------------------------------------------------------------+
//|                                               SampleExpert.mq5  |
//|                        Generated by Backtest System               |
//+------------------------------------------------------------------+
#property copyright "Copyright © 2024"
#property link      "https://yourwebsite.com"
#property version   "1.00"

input double SlPoints        = %.6f;    // Stop Loss
input double TpPoints        = %.6f;    // Take Profit
input double LotSize         = %.2f;    // Lot size
input double Commission      = %.6f;    // Commission per trade
input double TsIncrement     = %.6f;    // Trailing Stop increment
input int    MaPeriod        = %d;       // MA period
input double MaThreshold     = %.6f;    // MA threshold

void OnTick()
{
    // Your trading logic here
}
//+------------------------------------------------------------------+
